### ISSUE TITLE
Standardize theorist/experimentalist inputs and outputs

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora#278] opened 2023-02-28 19:08 UTC
We encounter the problem that different theorists/experimentalists expect and produce different data formats (e.g., numpy versus pandas) and with potentially different dimensions (e.g., 1D vs. 2D numpy array). We should consider standardizing the inputs & outputs, potentially using a pandas data frame.

**Comment by hollandjg** [comment] 2023-06-16 15:06
duplicate of #231

**Closed by hollandjg** 2023-06-16 15:06 UTC
Labels: experimentalist, theorist, PI priority
