### ISSUE TITLE
Use the same operation names for DARTS, BMS, and BSR 

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora#301] opened 2023-03-21 18:13 UTC
We should use the ones from BMS.

**Comment by hollandjg** [comment] 2023-04-04 14:36
Just use the `sympy` names?

**Comment by hollandjg** [comment] 2023-04-04 14:36
Related to #338

**Comment by gtdang** [comment] 2023-07-25 20:14
Duplicate of #234

**Closed** 2023-07-25 20:14 UTC
Labels: duplicate, enhancement, theorist, priority 3: optional
